name: Lint Check

on:
  push:
    branches: [ "main", "Developer" ]

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: Academic-Notification

      - name: Run ESLint
        run: npm run lint
        working-directory: Academic-Notification
