name: main
on:
  push:

jobs:
  ubuntu-test:
    name: Ubuntu Tests
    runs-on: Ubuntu-latest
    steps:
      - name: Install ESLint
        run: npm install
        
      - name: initialize ESLint
        run: npm init @eslint/config@latest
    
  # https://dev.to/thomaslombart/how-to-setup-eslint-and-prettier-for-your-react-apps-1n42

  # Need: linter, limit size (5 megs max), use Checkout to allow for the checks, use at least two platforms 
  # (runners) to run checks, determine triggers

  # npm install eslint
