name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Run Tests and Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Show directory and contents
        run: |
          pwd
          ls -la
        working-directory: Academic-Notification

      - name: Install dependencies
        run: npm ci
        working-directory: Academic-Notification

      - name: Run ESLint
        run: |
          echo "Running ESLint..."
          npm run lint
        working-directory: Academic-Notification

      - name: Build (if applicable)
        run: npm run build --if-present
        working-directory: Academic-Notification

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test
        working-directory: Academic-Notification
